### ISSUE TITLE
Cannot find XRoadRequestHandler

### ISSUE THREAD

**Issue by urmatt** [janno-p/XRoadLib#11]
Hi 

I wont to try use this lib & I follow this guide http://janno-p.github.io/XRoadLib/tutorial-dotnetcore.html
but on step Service request handler creation, I have a problem. Can't find XRoadLib.Handler.

**Comment by janno-p** [comment]
Hi,

It seems that the tutorial is a bit outdated. The missing parts that are specific to AspNetCore environment are now located in separate assembly `XRoadLib.Extensions.AspNetCore`. That dependency should be added via command line `dotnet add package XRoadLib.Extensions.AspNetCore`.

After that you should use namespace `using XRoadLib.Extensions.AspNetCore` instead of `XRoadLib.Handlers`.

I'll have to update the tutorials in some time.

**Comment by janno-p** [comment]
Tutorial updated to match latest version of the library: http://janno-p.github.io/XRoadLib/articles/tutorials/aspnetcore.html
