### ISSUE TITLE
XroadLib error when response is an asynchronous task

### ISSUE THREAD

**Issue by Evitxu** [janno-p/XRoadLib#17]
Hi, I would like to use the XRoadLib with asynchronous response but it is not working.
I have two interfaces: asynchronous and synchronous. The interface with synchronous response works fine but the asynchronous response fails. The wsdl is not generated, These are their implementations:

[SuppressMessage("ReSharper", "UnusedMember.Global")]
[XRoadService("getPerson")]
Responses.getPersonResponse getPerson(Requests.getPersonRequest getPersonRequest);

 [SuppressMessage("ReSharper", "UnusedMember.Global")]
[XRoadService("getPersonAsync")]
System.Threading.Tasks.Task<Responses.getPersonResponse> getPersonAsync(Requests.getPersonRequest getPersonRequest);

XRoad sends the error:
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode>Server.InternalError</faultcode>
      <faultstring>The '`' character, hexadecimal value 0x60, cannot be included in a name.</faultstring>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

If I replace in the file SchemaDefinitionProvider.cs (XRoadLib.Schema) the value \x60 for string.empty in the normalizedType variable, I can see the wsdl (wrong) generated and the response is Task1, instead getPersonResponse.

Could you please help me? I don't know what I'm doing wrong.

Thanks in advance.

Regards,

Eva

**Comment by janno-p** [comment]
Hi, I will look into it. Seems valid and acceptable use case which should be supported.

**Comment by janno-p** [comment]
Async service definitions are now supported (version 1.4.5) and should work same as sync definitions. WSDL definition should look identical to sync version (since async doesn't change request structure). Request handling has some more context in ResponseDefinition to provide info about when service should be called as async or not.

If you have custom implementation for service invocation (handler overrides), then check WebServiceRequestHandler class InvokeRuntimeMethodAsync method for ideas how to connect requests with service implementation.

**Comment by Evitxu** [comment]
Hi, I have tested the new version and it is working perfectly.

Now, I have some doubts about the connection with C# project and webservice XRoad. I'm going to open a new issue.

Many thanks.
