### ISSUE TITLE
Calculator example needs update

### ISSUE THREAD

**Issue by eramirez-sv** [janno-p/XRoadLib#5]
Reading the code I noticed that in XRoadLib/samples/Calculator/Startup.cs, the program is using Protocol Version 3.1. Could you update it to use the latest version? Or, let me know what changes I need to make to use newest version.
Thank you!

**Comment by eramirez-sv** [comment]
I figure it out. Just needed to use the DefaultSchemaExporter and protocol version 4.0 inside Startup.cs.

**Comment by janno-p** [comment]
Hi! Sorry for the late response, but at least I can confirm that `DefaultSchemaExporter` right thing to use for X-Road message protocol 4.0 style messages. The name parameter can be anything you like, it's primary purpose is to distinguish different protocols (in case adapter needs to support multiple X-Road protocols for same functionality), but since it is used in some places as X-Road version, "4.0" is the best choice.

I will review the example when I have some free time available.
